version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - NUTRIMATCH_DATABASE_HOST=db
      - NUTRIMATCH_DATABASE_PORT=5432
      - NUTRIMATCH_DATABASE_USER=postgres
      - NUTRIMATCH_DATABASE_PASSWORD=postgres
      - NUTRIMATCH_DATABASE_DBNAME=nutrimatch
      - NUTRIMATCH_DATABASE_SSLMODE=disable
    volumes:
      - ./configs:/root/configs
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nutrimatch
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
