// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.countFoodsStmt, err = db.PrepareContext(ctx, countFoods); err != nil {
		return nil, fmt.Errorf("error preparing query CountFoods: %w", err)
	}
	if q.createFoodStmt, err = db.PrepareContext(ctx, createFood); err != nil {
		return nil, fmt.Errorf("error preparing query CreateFood: %w", err)
	}
	if q.createRefreshTokenStmt, err = db.PrepareContext(ctx, createRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRefreshToken: %w", err)
	}
	if q.createUserStmt, err = db.PrepareContext(ctx, createUser); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUser: %w", err)
	}
	if q.createUserProfileStmt, err = db.PrepareContext(ctx, createUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query CreateUserProfile: %w", err)
	}
	if q.deleteExpiredRefreshTokensStmt, err = db.PrepareContext(ctx, deleteExpiredRefreshTokens); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteExpiredRefreshTokens: %w", err)
	}
	if q.deleteFoodStmt, err = db.PrepareContext(ctx, deleteFood); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteFood: %w", err)
	}
	if q.deleteUserStmt, err = db.PrepareContext(ctx, deleteUser); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUser: %w", err)
	}
	if q.deleteUserProfileStmt, err = db.PrepareContext(ctx, deleteUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query DeleteUserProfile: %w", err)
	}
	if q.getDefaultUserProfileStmt, err = db.PrepareContext(ctx, getDefaultUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query GetDefaultUserProfile: %w", err)
	}
	if q.getFoodByEAN13Stmt, err = db.PrepareContext(ctx, getFoodByEAN13); err != nil {
		return nil, fmt.Errorf("error preparing query GetFoodByEAN13: %w", err)
	}
	if q.getFoodByIDStmt, err = db.PrepareContext(ctx, getFoodByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetFoodByID: %w", err)
	}
	if q.getRefreshTokenStmt, err = db.PrepareContext(ctx, getRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query GetRefreshToken: %w", err)
	}
	if q.getUserByEmailStmt, err = db.PrepareContext(ctx, getUserByEmail); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByEmail: %w", err)
	}
	if q.getUserByIDStmt, err = db.PrepareContext(ctx, getUserByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserByID: %w", err)
	}
	if q.getUserProfileByIDStmt, err = db.PrepareContext(ctx, getUserProfileByID); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserProfileByID: %w", err)
	}
	if q.getUserProfilesStmt, err = db.PrepareContext(ctx, getUserProfiles); err != nil {
		return nil, fmt.Errorf("error preparing query GetUserProfiles: %w", err)
	}
	if q.listFoodsStmt, err = db.PrepareContext(ctx, listFoods); err != nil {
		return nil, fmt.Errorf("error preparing query ListFoods: %w", err)
	}
	if q.listFoodsByTypeStmt, err = db.PrepareContext(ctx, listFoodsByType); err != nil {
		return nil, fmt.Errorf("error preparing query ListFoodsByType: %w", err)
	}
	if q.revokeAllUserRefreshTokensStmt, err = db.PrepareContext(ctx, revokeAllUserRefreshTokens); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeAllUserRefreshTokens: %w", err)
	}
	if q.revokeRefreshTokenStmt, err = db.PrepareContext(ctx, revokeRefreshToken); err != nil {
		return nil, fmt.Errorf("error preparing query RevokeRefreshToken: %w", err)
	}
	if q.searchFoodsByNameStmt, err = db.PrepareContext(ctx, searchFoodsByName); err != nil {
		return nil, fmt.Errorf("error preparing query SearchFoodsByName: %w", err)
	}
	if q.setProfileAsDefaultStmt, err = db.PrepareContext(ctx, setProfileAsDefault); err != nil {
		return nil, fmt.Errorf("error preparing query SetProfileAsDefault: %w", err)
	}
	if q.updateUserStmt, err = db.PrepareContext(ctx, updateUser); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUser: %w", err)
	}
	if q.updateUserEmailVerificationStmt, err = db.PrepareContext(ctx, updateUserEmailVerification); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserEmailVerification: %w", err)
	}
	if q.updateUserLastLoginStmt, err = db.PrepareContext(ctx, updateUserLastLogin); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserLastLogin: %w", err)
	}
	if q.updateUserPasswordStmt, err = db.PrepareContext(ctx, updateUserPassword); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserPassword: %w", err)
	}
	if q.updateUserProfileStmt, err = db.PrepareContext(ctx, updateUserProfile); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateUserProfile: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.countFoodsStmt != nil {
		if cerr := q.countFoodsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing countFoodsStmt: %w", cerr)
		}
	}
	if q.createFoodStmt != nil {
		if cerr := q.createFoodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createFoodStmt: %w", cerr)
		}
	}
	if q.createRefreshTokenStmt != nil {
		if cerr := q.createRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRefreshTokenStmt: %w", cerr)
		}
	}
	if q.createUserStmt != nil {
		if cerr := q.createUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserStmt: %w", cerr)
		}
	}
	if q.createUserProfileStmt != nil {
		if cerr := q.createUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createUserProfileStmt: %w", cerr)
		}
	}
	if q.deleteExpiredRefreshTokensStmt != nil {
		if cerr := q.deleteExpiredRefreshTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteExpiredRefreshTokensStmt: %w", cerr)
		}
	}
	if q.deleteFoodStmt != nil {
		if cerr := q.deleteFoodStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteFoodStmt: %w", cerr)
		}
	}
	if q.deleteUserStmt != nil {
		if cerr := q.deleteUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserStmt: %w", cerr)
		}
	}
	if q.deleteUserProfileStmt != nil {
		if cerr := q.deleteUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing deleteUserProfileStmt: %w", cerr)
		}
	}
	if q.getDefaultUserProfileStmt != nil {
		if cerr := q.getDefaultUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getDefaultUserProfileStmt: %w", cerr)
		}
	}
	if q.getFoodByEAN13Stmt != nil {
		if cerr := q.getFoodByEAN13Stmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFoodByEAN13Stmt: %w", cerr)
		}
	}
	if q.getFoodByIDStmt != nil {
		if cerr := q.getFoodByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getFoodByIDStmt: %w", cerr)
		}
	}
	if q.getRefreshTokenStmt != nil {
		if cerr := q.getRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getRefreshTokenStmt: %w", cerr)
		}
	}
	if q.getUserByEmailStmt != nil {
		if cerr := q.getUserByEmailStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByEmailStmt: %w", cerr)
		}
	}
	if q.getUserByIDStmt != nil {
		if cerr := q.getUserByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserByIDStmt: %w", cerr)
		}
	}
	if q.getUserProfileByIDStmt != nil {
		if cerr := q.getUserProfileByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserProfileByIDStmt: %w", cerr)
		}
	}
	if q.getUserProfilesStmt != nil {
		if cerr := q.getUserProfilesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getUserProfilesStmt: %w", cerr)
		}
	}
	if q.listFoodsStmt != nil {
		if cerr := q.listFoodsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFoodsStmt: %w", cerr)
		}
	}
	if q.listFoodsByTypeStmt != nil {
		if cerr := q.listFoodsByTypeStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listFoodsByTypeStmt: %w", cerr)
		}
	}
	if q.revokeAllUserRefreshTokensStmt != nil {
		if cerr := q.revokeAllUserRefreshTokensStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeAllUserRefreshTokensStmt: %w", cerr)
		}
	}
	if q.revokeRefreshTokenStmt != nil {
		if cerr := q.revokeRefreshTokenStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing revokeRefreshTokenStmt: %w", cerr)
		}
	}
	if q.searchFoodsByNameStmt != nil {
		if cerr := q.searchFoodsByNameStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing searchFoodsByNameStmt: %w", cerr)
		}
	}
	if q.setProfileAsDefaultStmt != nil {
		if cerr := q.setProfileAsDefaultStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing setProfileAsDefaultStmt: %w", cerr)
		}
	}
	if q.updateUserStmt != nil {
		if cerr := q.updateUserStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserStmt: %w", cerr)
		}
	}
	if q.updateUserEmailVerificationStmt != nil {
		if cerr := q.updateUserEmailVerificationStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserEmailVerificationStmt: %w", cerr)
		}
	}
	if q.updateUserLastLoginStmt != nil {
		if cerr := q.updateUserLastLoginStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserLastLoginStmt: %w", cerr)
		}
	}
	if q.updateUserPasswordStmt != nil {
		if cerr := q.updateUserPasswordStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserPasswordStmt: %w", cerr)
		}
	}
	if q.updateUserProfileStmt != nil {
		if cerr := q.updateUserProfileStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateUserProfileStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                              DBTX
	tx                              *sql.Tx
	countFoodsStmt                  *sql.Stmt
	createFoodStmt                  *sql.Stmt
	createRefreshTokenStmt          *sql.Stmt
	createUserStmt                  *sql.Stmt
	createUserProfileStmt           *sql.Stmt
	deleteExpiredRefreshTokensStmt  *sql.Stmt
	deleteFoodStmt                  *sql.Stmt
	deleteUserStmt                  *sql.Stmt
	deleteUserProfileStmt           *sql.Stmt
	getDefaultUserProfileStmt       *sql.Stmt
	getFoodByEAN13Stmt              *sql.Stmt
	getFoodByIDStmt                 *sql.Stmt
	getRefreshTokenStmt             *sql.Stmt
	getUserByEmailStmt              *sql.Stmt
	getUserByIDStmt                 *sql.Stmt
	getUserProfileByIDStmt          *sql.Stmt
	getUserProfilesStmt             *sql.Stmt
	listFoodsStmt                   *sql.Stmt
	listFoodsByTypeStmt             *sql.Stmt
	revokeAllUserRefreshTokensStmt  *sql.Stmt
	revokeRefreshTokenStmt          *sql.Stmt
	searchFoodsByNameStmt           *sql.Stmt
	setProfileAsDefaultStmt         *sql.Stmt
	updateUserStmt                  *sql.Stmt
	updateUserEmailVerificationStmt *sql.Stmt
	updateUserLastLoginStmt         *sql.Stmt
	updateUserPasswordStmt          *sql.Stmt
	updateUserProfileStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                              tx,
		tx:                              tx,
		countFoodsStmt:                  q.countFoodsStmt,
		createFoodStmt:                  q.createFoodStmt,
		createRefreshTokenStmt:          q.createRefreshTokenStmt,
		createUserStmt:                  q.createUserStmt,
		createUserProfileStmt:           q.createUserProfileStmt,
		deleteExpiredRefreshTokensStmt:  q.deleteExpiredRefreshTokensStmt,
		deleteFoodStmt:                  q.deleteFoodStmt,
		deleteUserStmt:                  q.deleteUserStmt,
		deleteUserProfileStmt:           q.deleteUserProfileStmt,
		getDefaultUserProfileStmt:       q.getDefaultUserProfileStmt,
		getFoodByEAN13Stmt:              q.getFoodByEAN13Stmt,
		getFoodByIDStmt:                 q.getFoodByIDStmt,
		getRefreshTokenStmt:             q.getRefreshTokenStmt,
		getUserByEmailStmt:              q.getUserByEmailStmt,
		getUserByIDStmt:                 q.getUserByIDStmt,
		getUserProfileByIDStmt:          q.getUserProfileByIDStmt,
		getUserProfilesStmt:             q.getUserProfilesStmt,
		listFoodsStmt:                   q.listFoodsStmt,
		listFoodsByTypeStmt:             q.listFoodsByTypeStmt,
		revokeAllUserRefreshTokensStmt:  q.revokeAllUserRefreshTokensStmt,
		revokeRefreshTokenStmt:          q.revokeRefreshTokenStmt,
		searchFoodsByNameStmt:           q.searchFoodsByNameStmt,
		setProfileAsDefaultStmt:         q.setProfileAsDefaultStmt,
		updateUserStmt:                  q.updateUserStmt,
		updateUserEmailVerificationStmt: q.updateUserEmailVerificationStmt,
		updateUserLastLoginStmt:         q.updateUserLastLoginStmt,
		updateUserPasswordStmt:          q.updateUserPasswordStmt,
		updateUserProfileStmt:           q.updateUserProfileStmt,
	}
}
