// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Allergen struct {
	ID          int32                 `json:"id"`
	Name        string                `json:"name"`
	Description sql.NullString        `json:"description"`
	CommonNames pqtype.NullRawMessage `json:"common_names"`
	CreatedAt   sql.NullTime          `json:"created_at"`
}

type AuditLog struct {
	ID         uuid.UUID             `json:"id"`
	UserID     uuid.NullUUID         `json:"user_id"`
	Action     string                `json:"action"`
	EntityType string                `json:"entity_type"`
	EntityID   string                `json:"entity_id"`
	Details    pqtype.NullRawMessage `json:"details"`
	IpAddress  sql.NullString        `json:"ip_address"`
	UserAgent  sql.NullString        `json:"user_agent"`
	CreatedAt  sql.NullTime          `json:"created_at"`
}

type Food struct {
	ID                 string                `json:"id"`
	Name               string                `json:"name"`
	AlternateNames     pqtype.NullRawMessage `json:"alternate_names"`
	Description        sql.NullString        `json:"description"`
	FoodType           sql.NullString        `json:"food_type"`
	Source             pqtype.NullRawMessage `json:"source"`
	Serving            pqtype.NullRawMessage `json:"serving"`
	Nutrition100g      pqtype.NullRawMessage `json:"nutrition_100g"`
	Ean13              sql.NullString        `json:"ean_13"`
	Labels             pqtype.NullRawMessage `json:"labels"`
	PackageSize        pqtype.NullRawMessage `json:"package_size"`
	Ingredients        sql.NullString        `json:"ingredients"`
	IngredientAnalysis pqtype.NullRawMessage `json:"ingredient_analysis"`
	CreatedAt          sql.NullTime          `json:"created_at"`
	UpdatedAt          sql.NullTime          `json:"updated_at"`
}

type FoodRating struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"user_id"`
	FoodID    string         `json:"food_id"`
	Rating    int16          `json:"rating"`
	Comments  sql.NullString `json:"comments"`
	CreatedAt sql.NullTime   `json:"created_at"`
	UpdatedAt sql.NullTime   `json:"updated_at"`
}

type HealthCondition struct {
	ID                      int32                 `json:"id"`
	Name                    string                `json:"name"`
	Description             sql.NullString        `json:"description"`
	NutrientRestrictions    pqtype.NullRawMessage `json:"nutrient_restrictions"`
	NutrientRecommendations pqtype.NullRawMessage `json:"nutrient_recommendations"`
	CreatedAt               sql.NullTime          `json:"created_at"`
}

type RefreshToken struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
	Revoked   sql.NullBool `json:"revoked"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

type User struct {
	ID            uuid.UUID      `json:"id"`
	Email         string         `json:"email"`
	PasswordHash  string         `json:"password_hash"`
	FirstName     sql.NullString `json:"first_name"`
	LastName      sql.NullString `json:"last_name"`
	DateOfBirth   sql.NullTime   `json:"date_of_birth"`
	Gender        sql.NullString `json:"gender"`
	HeightCm      sql.NullString `json:"height_cm"`
	WeightKg      sql.NullString `json:"weight_kg"`
	ActivityLevel sql.NullString `json:"activity_level"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	UpdatedAt     sql.NullTime   `json:"updated_at"`
	LastLogin     sql.NullTime   `json:"last_login"`
	AccountStatus sql.NullString `json:"account_status"`
	EmailVerified sql.NullBool   `json:"email_verified"`
	MfaEnabled    sql.NullBool   `json:"mfa_enabled"`
	MfaSecret     sql.NullString `json:"mfa_secret"`
}

type UserProfile struct {
	ID                      uuid.UUID             `json:"id"`
	UserID                  uuid.UUID             `json:"user_id"`
	ProfileName             string                `json:"profile_name"`
	IsDefault               sql.NullBool          `json:"is_default"`
	HealthConditions        pqtype.NullRawMessage `json:"health_conditions"`
	DietaryRestrictions     pqtype.NullRawMessage `json:"dietary_restrictions"`
	Allergens               pqtype.NullRawMessage `json:"allergens"`
	GoalType                sql.NullString        `json:"goal_type"`
	CalorieTarget           sql.NullInt32         `json:"calorie_target"`
	MacronutrientPreference sql.NullString        `json:"macronutrient_preference"`
	DislikedFoods           pqtype.NullRawMessage `json:"disliked_foods"`
	PreferredFoods          pqtype.NullRawMessage `json:"preferred_foods"`
	CuisinePreferences      pqtype.NullRawMessage `json:"cuisine_preferences"`
	CreatedAt               sql.NullTime          `json:"created_at"`
	UpdatedAt               sql.NullTime          `json:"updated_at"`
}

type UserSavedFood struct {
	ID        uuid.UUID    `json:"id"`
	UserID    uuid.UUID    `json:"user_id"`
	FoodID    string       `json:"food_id"`
	ListType  string       `json:"list_type"`
	CreatedAt sql.NullTime `json:"created_at"`
}
